### ISSUE TITLE
strictdoc server does not render .PNG image

### ISSUE THREAD

**Issue by elfman2** [strictdoc-project/strictdoc#1161]
version 0.0.41a
In https://github.com/strictdoc-project/strictdoc-examples/examples
strictdoc server .
In example 5:
INFO:     192.168.1.44:49902 - "GET /examples/_assets/sandbox1.png HTTP/1.1" 404 Not Found

**Comment by elfman2** [comment]
.jpg not rendered either

seem to handle only .svg

**Comment by stanislaw** [comment]
Please check [0.0.41a2](https://pypi.org/project/strictdoc/0.0.41a2/). Should be fixed now.

**Comment by elfman2** [comment]
Ok when checking out 0.0.41a2,

but when I pip install strictdoc 0.0.41a2,
 I still get 0.0.41a1!?
